{
    imports = [
        ./audacious.nix
        ./bitwig.nix
        ./blender.nix
        ./kdeconnect.nix
        ./kdenlive.nix
        ./kicad.nix
        ./direnv.nix
        ./firefox.nix
        ./obs.nix
        ./rustrover.nix
        ./vlc.nix
        ./dorion.nix
        ./krita.nix
        ./bottles.nix
        ./minecraft.nix
        ./protonmail.nix
        ./vscode.nix
        ./ytdlp.nix
    ];
}
