{...}: {
  imports = [
    ./anki.nix
    ./audacious.nix
    ./audiotube.nix
    ./blender.nix
    ./kdeconnect.nix
    ./kdenlive.nix
    ./direnv.nix
    ./firefox.nix
    ./ktorrent.nix
    ./libreoffice.nix
    ./obs.nix
    ./openutau.nix
    ./rustrover.nix
    ./vlc.nix
    ./gimp.nix
    ./discord.nix
    ./krita.nix
    ./bottles.nix
    ./minecraft.nix
    #./protonmail.nix
    ./vscode.nix
    ./ytdlp.nix
    ./okteta.nix
    ./keyboard.nix
    ./irc.nix
    ./ghidra.nix
    ./emulators.nix
    ./ftp.nix
    ./logseq.nix
    ./randomkde.nix
  ];
}
