{
  imports = [
    ./audacious.nix
    ./audiotube.nix
    ./bitwig.nix
    ./blender.nix
    ./kdeconnect.nix
    ./kdenlive.nix
    ./kicad.nix
    ./direnv.nix
    ./firefox.nix
    ./ktorrent.nix
    ./libreoffice.nix
    ./obs.nix
    ./openutau.nix
    ./rustrover.nix
    ./vlc.nix
    ./dorion.nix
    ./krita.nix
    ./bottles.nix
    ./minecraft.nix
    ./protonmail.nix
    ./vscode.nix
    ./ytdlp.nix
  ];
}
